name: Continuous Integration

on:
    push:
        branches: [master]

jobs:
    test_push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1.1.0
              with:
                  node-version: latest
            - run: yarn install
            - run: yarn lint
            - run: yarn test
            - run: yarn build
